#!/bin/bash

remove_top() {
    local top=1 line
    while IFS= read -r line; do
        if [ "$top" ]; then
            if [ "$line" ] && [[ "$line" != "# "* ]]; then
                top=
                printf '%s\n' "$line"
            fi
        else
            printf '%s\n' "$line"
        fi
    done
}

sed --silent '/^# .*'"$1"'$/,/^# /p' <CHANGES.md |
    tac |
    remove_top |
    tac
