#!/usr/bin/env python

import json
import os
import sys
from subprocess import check_output


def _encode_json(o):
    return json.dumps(o, separators=(",", ":"))


def main():
    with open(sys.argv[1]) as targets_file:
        targets = json.load(targets_file)

    tags = check_output("git tag -l".split(), text=True).strip().splitlines()

    targets_per_tags = [dict(tag=tag, **target) for target in targets for tag in tags]

    tags = "tags={}\n".format(_encode_json(tags))
    targets = "targets={}\n".format(_encode_json(targets))
    targets_per_tags = "targets_per_tags={}\n".format(_encode_json(targets_per_tags))

    print(tags)
    print(targets)
    print(targets_per_tags)

    with open(os.environ["GITHUB_OUTPUT"], "a") as output:
        output.write(tags)
        output.write(targets)
        output.write(targets_per_tags)


if __name__ == "__main__":
    main()
